# This has to be a separate action because actions on pull requests are not allowed write actions.
#
# See: https://github.com/marketplace/actions/junit-report-action#pr-run-permissions
# See: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

name: report
on:
  workflow_run:
    workflows: [ test ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Hvor er jeg
        run: echo $PWD && find .
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: './report.xml'
