name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Run tests
        run: cd test && deno task test-ci

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: 'test/report.xml'
          retention-days: 1

